### ISSUE TITLE
LingoSwitch interferes with MacOS default Input Source-Switcher | Design-Enhancement (Smoother Edges) - similar to "Ventura"-styled Pop-Up

### ISSUE THREAD

**Issue by D-JOSEPHY** [mcjkula/lingoswitch#3]
Thank you so much for creating this app!!! Truly a relief.
Here are some issues I found:
- The app runs next to the Mac one, but sometimes the language switched to is not the same one. In other words, sometimes the LingoSwitch input source differs from the OS one. I *think* this is because the switching is LingoSwitch is faster than the OS one.
- The interface is different from the OS one. It'd be nice to have smoother edges.

**Comment by mcjkula** [comment]
Thank you for your feedback! 

For the first issue, I think that is because your OS language switcher is still binded to the "🌐"-Key, which causes both apps to switch the input.

**To change that you can follow this:**
Go to Settings > Keyboard and set "Press "🌐"-Key" to "_Do Nothing_".

This should unbind the OS language switcher, which causes the unexpected behavior.

---

For the second issue I understand there may be a difference in design from the previous "Ventura" pop-up to mine. I looked at some screenshots and realized the smoother edges as well, I will implement those in the next version.

Hope that will solve those mentioned issues!

**Comment by D-JOSEPHY** [comment]
Ok, thanks! It's great that the 🌐 still works with LingoSwitch but not with the OS! Funny that the small icon still appears (it doesn't bother me). 
Thanks for addressing the difference in design. It's not a huge deal, but I do appreciate the effort! Is there a way I could donate some money to thank you for the app?

**Comment by mcjkula** [comment]
That's nice to hear it helped! I deeply appreciate your offer to support my work! I didn't have any setup to accept donations so far, as I honestly didn't think about it before. I already appreciate it a lot, when others find use in a project of mine.

I would consider setting up "**GitHub Sponsors**" to allow for donations in the future.

I hope you continue to enjoy using "LingoSwitch"! Don't hesitate to open an issue for any other concerns or suggestions you may have in the future.
